export const ORDER_CONNECTION_INIT: 'ORDER_CONNECTION_INIT' = 'ORDER_CONNECTION_INIT';
export const ORDER_CONNECTION_CLOSE: 'ORDER_CONNECTION_CLOSE' = 'ORDER_CONNECTION_CLOSE';
export const ORDER_CONNECTION_SUCCESS: 'ORDER_CONNECTION_SUCCESS' = 'ORDER_CONNECTION_SUCCESS';
export const ORDER_GET_MESSAGE: 'ORDER_GET_MESSAGE' = 'ORDER_GET_MESSAGE';
export const ORDER_CONNECTION_ERROR: 'ORDER_CONNECTION_ERROR' = 'ORDER_CONNECTION_ERROR';