export const SET_USER: 'SET_USER' = 'SET_USER';

export const REGISTER_REQUEST: 'REGISTER_REQUEST' = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';

export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';

export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';

export const GET_TOKEN_REQUEST: 'GET_TOKEN_REQUEST' = 'GET_TOKEN_REQUEST';
export const GET_TOKEN_SUCCESS: 'GET_TOKEN_SUCCESS' = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAILED: 'GET_TOKEN_FAILED' = 'GET_TOKEN_FAILED';

export const GET_CODE_REQUEST: 'GET_CODE_REQUEST' = 'GET_CODE_REQUEST';
export const GET_CODE_SUCCESS: 'GET_CODE_SUCCESS' = 'GET_CODE_SUCCESS';
export const GET_CODE_FAILED: 'GET_CODE_FAILED' = 'GET_CODE_FAILED';

export const CREATE_PASSWORD_REQUEST: 'CREATE_PASSWORD_REQUEST' = 'CREATE_PASSWORD_REQUEST';
export const CREATE_PASSWORD_SUCCESS: 'CREATE_PASSWORD_SUCCESS' = 'CREATE_PASSWORD_SUCCESS';
export const CREATE_PASSWORD_FAILED: 'CREATE_PASSWORD_FAILED' = 'CREATE_PASSWORD_FAILED';

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';

export const UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST' = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS' = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED: 'UPDATE_PROFILE_FAILED' = 'UPDATE_PROFILE_FAILED';